[package]
name = "native_scanner"
version = "0.1.0"
edition = "2021"

[lib]
name = "native_scanner"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
rayon = "1.10.0"
sha2 = "0.10.8"
walkdir = "2.5.0"
